### PR TITLE
Updated links

### LINKED ISSUE #5: Update links to repo
Since this repo is now moved to the [DiscordHooks](https://github.com/DiscordHooks) org., we should now update all the links in this repo from `k3rn31p4nic/appveyor-discord-webhook` to `DiscordHooks/appveyor-discord-webhook`.

*PRs are welcome.*

### PR DESCRIPTION
**Pull request by soulspark666**
Fixed #5

### CODE REVIEW

**Comment by iamtraction** [comment]
Did you also change the line endings from `CRLF` to `LF`?

**Review by iamtraction — CHANGES_REQUESTED** [review]
Please revert the line endings back to `CRLF` as this is supposed to be used in Windows, `LF` line endings will cause reading issues if someone opens it in Notepad.

**Comment by soulspark666** [comment]
I can't seem to find the line endings that you are implying in your comment, please explain it furthermore and I see to it as quickly as I can.

**Comment by iamtraction** [comment]
Which code editor are you using?

If you're using Notepad++ you can find it in the right side of the status bar:

image

Or if you're using Atom, you can find it in the same place:
  
image

**Comment by soulspark666** [comment]
I checked it and the line endings are in CRLF. Here is the screenshot:
screenshot 10

**Comment by iamtraction** [comment]
Add the all the other files are using `LF`? Then I wonder why the [diff](https://github.com/DiscordHooks/appveyor-discord-webhook/pull/6/files) is showing that all the lines are modified. I'll look into it.

**Review by iamtraction — APPROVED** [review]
👌

**Comment by iamtraction** [comment]
Thank you for your contribution! We would like to thank you by **inviting you to join the DiscordHooks organization on GitHub.** Accept the invite by visiting https://github.com/orgs/DiscordHooks/invitation.

Thanks again!

**Pull request merged**
